apiVersion: v1
kind: ConfigMap
metadata:
  name: django-config
data:
  DEBUG: "{{ .Values.env.DEBUG }}"
  SECRET_KEY: "{{ .Values.env.SECRET_KEY }}"
  ALLOWED_HOSTS: "{{ .Values.env.ALLOWED_HOSTS }}"
  DATABASE_URL: "{{ .Values.env.DATABASE_URL }}"
